<?xml version="1.0"?>
<robot name="moon" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included files -->
  <xacro:include filename="$(find moon_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find moon_description)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find moon_description)/urdf/wheels.urdf.xacro"/>

  <!-- Robot properties -->
  <xacro:property name="base_width" value="0.325"/>
  <xacro:property name="base_length" value="0.3"/>
  <xacro:property name="base_height" value="0.07"/>

  <xacro:property name="caster_radius" value="0.008"/>

  <xacro:property name="wheel_width" value="0.015"/>
  <xacro:property name="wheel_radius" value="0.0375"/>

  <xacro:property name="wheel_holder_size" value="0.01"/>

  <xacro:property name="lidar_height" value="0.02"/>
  <xacro:property name="lidar_radius" value="0.045"/>

  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.001"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://moon_description/meshes/moon_base.stl"/>
      </geometry>
      <xacro:white_material/>
    </visual>
  </link>

  <link name="base_link_inertia">
    <xacro:box_collision width="${base_width}" depth="${base_height}" height="${base_length}"/>
    <inertial>
      <mass value="3.309"/>
      <origin xyz="0.00331 0 0.03506"/>
      <inertia ixx="2.547e-2" ixy="0.0" ixz="2.993e-6"
               iyy="2.374e-2" iyz="0.0"
               izz="4.650e-2"/>
    </inertial>
  </link>

  <joint name="base_link_inertia_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_link_inertia"/>
  </joint>

  <xacro:caster_wheel prefix="front_left" radius="${caster_radius}" x="0.0675" y="0.0725" z="0"/>
  <xacro:caster_wheel prefix="front_right" radius="${caster_radius}" x="0.0675" y="-0.0725" z="0"/>

  <xacro:transmission_wheel prefix="back_left" radius="${wheel_radius}" width="${wheel_width}"
                            holder_size="${wheel_holder_size}" direction="1.0" x="-0.0125" y="0.14"
                            z="${wheel_radius - caster_radius}"/>
  <xacro:transmission_wheel prefix="back_right" radius="${wheel_radius}" width="${wheel_width}"
                            holder_size="${wheel_holder_size}" direction="-1.0" x="-0.0125" y="-0.14"
                            z="${wheel_radius - caster_radius}"/>

  <xacro:caster_wheel prefix="back_left" radius="${caster_radius}" x="-0.1125" y="0.0725" z="0"/>
  <xacro:caster_wheel prefix="back_right" radius="${caster_radius}" x="-0.1125" y="-0.0725" z="0"/>

  <link name="lidar">
    <visual>
      <xacro:cylinder_geometry radius="${lidar_radius}" height="${lidar_height}"/>
      <xacro:green_material/>
    </visual>
    <xacro:cylinder_collision radius="${lidar_radius}" height="${lidar_height}"/>
    <xacro:cylinder_inertia mass="0.1" radius="${lidar_radius}" height="${lidar_height}"/>
    <dynamics damping="0.01" friction="100.0"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-0.04 0 ${base_height + lidar_height/2}"/>
    <parent link="base_link"/>
    <child link="lidar"/>
  </joint>

</robot>
