<?xml version="1.0"?>
<robot name="moon" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Global constants -->
  <xacro:property name="pi" value="3.1415926535897931"/>

  <!-- Included files -->
  <xacro:include filename="$(find moon_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find moon_description)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find moon_description)/urdf/wheels.urdf.xacro"/>

  <!-- Robot properties -->
  <xacro:property name="base_width" value="0.2"/>
  <xacro:property name="base_length" value="0.26"/>
  <xacro:property name="base_height" value="0.06"/>

  <xacro:property name="caster_radius" value="0.03"/>

  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_radius" value="0.035"/>

  <xacro:property name="wheel_holder_size" value="0.01"/>

  <xacro:property name="lidar_height" value="0.02"/>
  <xacro:property name="lidar_radius" value="0.04"/>

  <link name="base_footprint">
    <visual>
      <xacro:box_geometry width="0.001" depth="0.001" height="0.001"/>
      <xacro:white_material/>
    </visual>
    <xacro:box_inertia mass="0.0001" width="0.001" depth="0.001" height="0.001"/>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.03"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://moon_description/meshes/moon_base.stl"/>
      </geometry>
      <xacro:white_material/>
    </visual>
    <xacro:box_collision width="${base_width}" depth="${base_height}" height="${base_length}"/>
    <xacro:box_inertia mass="3" width="${base_width}" depth="${base_height}" height="${base_length}"/>
  </link>

  <xacro:caster_wheel prefix="front_left" radius="${caster_radius}" x="0.05" y="-0.1" z="0"/>
  <xacro:caster_wheel prefix="front_right" radius="${caster_radius}" x="-0.05" y="-0.1" z="0"/>

  <xacro:transmission_wheel prefix="back_left" radius="${wheel_radius}" width="${wheel_width}"
                            holder_size="${wheel_holder_size}" wheels_distance="0.05" direction="1.0"/>
  <xacro:transmission_wheel prefix="back_right" radius="${wheel_radius}" width="${wheel_width}"
                            holder_size="${wheel_holder_size}" wheels_distance="0.05" direction="-1.0"/>

  <link name="lidar">
    <visual>
      <xacro:cylinder_geometry radius="${lidar_radius}" height="${lidar_height}"/>
      <xacro:green_material/>
    </visual>
    <xacro:cylinder_collision radius="${lidar_radius}" height="${lidar_height}"/>
    <xacro:cylinder_inertia mass="0.1" radius="${lidar_radius}" height="${lidar_height}"/>
    <dynamics damping="0.01" friction="100.0"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.04 ${base_height + lidar_height/2}"/>
    <parent link="base_link"/>
    <child link="lidar"/>
  </joint>

</robot>
