laser_scan_matcher_node:
  fixed_frame: map
  base_frame: base_footprint

  use_imu: true
  use_odom: true
  use_vel: true

  use_cloud_input: false
  cloud_range_min: 0.4
  cloud_range_max: 10.0

  kf_dist_linear: 0.1
  kf_dist_angular: 0.175

  publish_tf: true
  publish_pose: true
  publish_pose_stamped: false

  max_iterations: 50
  max_correspondence_dist: 0.3
  max_angular_correction_deg: 45.0
  max_linear_correction: 0.5
  epsilon_xy: 0.000001
  epsilon_theta: 0.000001
  outliers_maxPerc: 0.90
